### ISSUE TITLE
Shutting down randomly

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-buildroot#6]
I'm facing some random shutdowns, mainly on EmulationStation interface. If I don't have any activity for about 10 minutes my RPi is shutting down. In-game I got few freezing (black screens) if I don't have any activity after 30 minutes approximately or quit a game after let it running for many time.

I'm using Extreme (default) overclocking and heatsinks

**Comment by digitalLumberjack** [comment]
Could you try to change your overclocking to TURBO mode or HIGH and tell me if the rpi still reboot ?
I've run recalbox on many many pi, and the only issue i had was not a reboot, but very few freezes...

**Comment by mgoulartBR** [comment]
I think that solved my problem! Thanks again!
